In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
df = pd.read_csv("./Hitters.csv")
df = df.dropna()
dms = pd.get_dummies(df[["League", "Division", "NewLeague"]])
y = df["Salary"]
x_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis = 1).astype("float64")
x = pd.concat([x_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis = 1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 99)

In [5]:
enet_model = ElasticNet().fit(x_train, y_train)

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/linear_model/_coordinate_descent.py:532: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 8444878.0001749, tolerance: 3261.989429590099
  positive)


In [6]:
enet_model.coef_

array([ -0.57886347,   2.16448445,   5.3605758 ,  -1.47206303,
         0.23418192,   2.38717742,   1.22813868,  -0.32536952,
         0.52005787,  -0.91842963,   1.78088179,   0.55437027,
        -0.28260924,   0.31322714,   0.25036516,  -5.29879463,
        21.66946074, -17.37588196,   9.67492316])

In [7]:
enet_model.intercept_

153.81005430623725

In [9]:
enet_model.predict(x_train)[0:10]

array([713.51611548, 423.67375151, 251.48960556, 359.69155299,
       626.717819  , 168.53933312, 267.64890623, 839.13099983,
       354.1299335 , 305.73837691])

In [11]:
from sklearn.metrics import mean_squared_error
pred_y = enet_model.predict(x_test)
np.sqrt(mean_squared_error(y_test, pred_y))

439.1238928152074

In [13]:
from sklearn.linear_model import ElasticNetCV
enet_cv_model = ElasticNetCV(cv = 10).fit(x_train, y_train)

In [14]:
enet_cv_model.alpha_

925.5320862465707

In [15]:
enet_cv_model.intercept_

122.71626759164621

In [16]:
enet_cv_model.coef_

array([ 0.24323744,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.30706854,  0.7392322 ,  0.        ,
        1.14037982,  0.24773376,  0.05468345,  0.31176132, -0.01871712,
       -0.        ,  0.        , -0.        ,  0.        ])

In [17]:
#Tuning the Elastic Net model with the optimum values
enet_tuned = ElasticNet(alpha = enet_cv_model.alpha_).fit(x_train, y_train)

In [18]:
pred_y = enet_tuned.predict(x_test)
np.sqrt(mean_squared_error(y_test, pred_y))

462.56547999370406