In [2]:
import pandas as pd
df = pd.read_csv("./Advertising.csv")
df = df.iloc[:,1:len(df)]
x = df.drop("sales", axis = 1)
y = df[["sales"]]

In [3]:
import statsmodels.api as sm
lm = sm.OLS(y, x)

In [4]:
model = lm.fit()

In [5]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Fri, 17 Sep 2021   Prob (F-statistic):                   2.43e-171
Time:                        11:03:53   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
#scikit learn model
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x, y)

In [7]:
model.intercept_

array([2.93888937])

In [8]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [10]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y, model.predict(x))

In [11]:
MSE

2.784126314510936

In [12]:
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 99)

In [14]:
x_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [15]:
model = lm.fit(x_train, y_train)
#RMSE in train error
np.sqrt(mean_squared_error(y_train, model.predict(x_train)))

1.7236824822650754

In [16]:
#RMSE in test error
np.sqrt(mean_squared_error(y_test, model.predict(x_test)))

1.4312783138301641

In [17]:
#k-fold cross validation
from sklearn.model_selection import cross_val_score
cross_val_score(model, x_train, y_train, cv = 10, scoring = "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])